In [ ]:
!pip install tensorflow pandas scikit-learn

Requirement already satisfied: tensorflow in /usr/local/lib/python3.12/dist-packages (2.19.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from tensorflow) (26.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (5.29.6)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.32.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from tensorflow) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.1.1)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.78.0)
Requirement already satisfied: tensorboard~=2.19.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.19.0)
Requirement already satisfied: keras>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.10.0)
Requirement already satisfied: numpy<2.2.0,>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.0.2)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.15.1)
Requirement already satisfied: ml-dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.5.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from astunparse>=1.6.0->tensorflow) (0.46.3)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (0.19.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2026.2.25)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.10.2)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from werkzeug>=1.0.1->tensorboard~=2.19.0->tensorflow) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow) (0.1.2)

In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report

In [ ]:
dataset = pd.read_csv("/content/Aggregrated_Data.csv")
dataset.head()

,timestamp,satellite_prn,satellite_elevation_deg,satellite_azimuth_deg,temperature_C,humidity_%,rain_intensity_mm_hr,rain_sensor_value,snr_measured_dbhz,label
0,2024-01-01 00:00,8.23,44.94,313.18,34.99,58.64,0.00,0.00,51,0
1,2024-01-01 00:00,2.94,22.20,200.38,33.96,55.17,0.57,0.00,47,0
2,2024-01-01 00:00,11.30,26.44,162.51,32.92,50.66,0.00,0.00,42,0
3,2024-01-01 00:00,26.70,77.68,58.32,31.32,40.02,1.36,0.00,44,0
4,2024-01-01 00:00,21.89,82.50,54.38,28.65,89.37,2.79,49.88,39,1

In [ ]:
dataset = dataset[
    (dataset["satellite_elevation_deg"] >= 10) &
    (dataset["satellite_elevation_deg"] <= 70) &
    (dataset["satellite_azimuth_deg"] >= 0) &
    (dataset["satellite_azimuth_deg"] <= 360) &
    (dataset["satellite_prn"] >= 1) &
    (dataset["satellite_prn"] <= 32)
]

In [ ]:
print(dataset.isnull().sum())

timestamp                  0
satellite_prn              0
satellite_elevation_deg    0
satellite_azimuth_deg      0
temperature_C              0
humidity_%                 0
rain_intensity_mm_hr       0
rain_sensor_value          0
snr_measured_dbhz          0
label                      0
dtype: int64

In [ ]:
(dataset == 0).sum()

timestamp                     0
satellite_prn                 0
satellite_elevation_deg       0
satellite_azimuth_deg       659
temperature_C               618
humidity_%                  629
rain_intensity_mm_hr       4119
rain_sensor_value          4359
snr_measured_dbhz             0
label                      8146
dtype: int64

In [ ]:
columns = [
    "satellite_prn",
    "satellite_elevation_deg",
    "satellite_azimuth_deg",
    "temperature_C",
    "humidity_%",
    "rain_sensor_value",
    "snr_measured_dbhz"
]

for col in columns:
    mean_val = dataset.loc[dataset[col] != 0, col].mean()
    dataset[col] = dataset[col].replace(0, mean_val)

In [ ]:
X = dataset[
    [
    "satellite_prn",
    "satellite_elevation_deg",
    "satellite_azimuth_deg",
    "temperature_C",
    "humidity_%",
    "rain_sensor_value",
    "snr_measured_dbhz"
    ]
]

y = dataset["label"]

In [ ]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled,
    y,
    test_size=0.2,
    random_state=42
)

In [ ]:
model = tf.keras.Sequential([

    tf.keras.layers.Dense(
        8,
        activation="relu",
        input_shape=(7,)
    ),

    tf.keras.layers.Dense(
        3,
        activation="softmax"
    )

])

In [ ]:
model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

In [ ]:
model.fit(
    X_train,
    y_train,
    epochs=30,
    batch_size=32,
    validation_split=0.2
)

Epoch 1/30
407/407 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.4600 - loss: 1.2510 - val_accuracy: 0.9613 - val_loss: 0.3049
Epoch 2/30
407/407 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9760 - loss: 0.2266 - val_accuracy: 0.9886 - val_loss: 0.1014
Epoch 3/30
407/407 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9910 - loss: 0.0865 - val_accuracy: 0.9895 - val_loss: 0.0596
Epoch 4/30
407/407 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9913 - loss: 0.0545 - val_accuracy: 0.9899 - val_loss: 0.0436
Epoch 5/30
407/407 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9926 - loss: 0.0420 - val_accuracy: 0.9902 - val_loss: 0.0354
Epoch 6/30
407/407 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9911 - loss: 0.0352 - val_accuracy: 0.9908 - val_loss: 0.0306
Epoch 7/30
407/407 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9925 - loss: 0.0298 - val_accuracy: 0.9914 - val_loss: 0.0272
Epoch 8/30
407/407 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.9926 - loss: 0.0279 - val_accuracy: 0.9914 - val_loss: 0.0253
Epoch 9/30
407/407 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9933 - loss: 0.0249 - val_accuracy: 0.9914 - val_loss: 0.0239
Epoch 10/30
407/407 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.9925 - loss: 0.0244 - val_accuracy: 0.9917 - val_loss: 0.0223
Epoch 11/30
407/407 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.9924 - loss: 0.0260 - val_accuracy: 0.9923 - val_loss: 0.0215
Epoch 12/30
407/407 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.9926 - loss: 0.0206 - val_accuracy: 0.9920 - val_loss: 0.0213
Epoch 13/30
407/407 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9921 - loss: 0.0233 - val_accuracy: 0.9929 - val_loss: 0.0204
Epoch 14/30
407/407 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9940 - loss: 0.0182 - val_accuracy: 0.9926 - val_loss: 0.0203
Epoch 15/30
407/407 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.9932 - loss: 0.0192 - val_accuracy: 0.9932 - val_loss: 0.0198
Epoch 16/30
407/407 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.9934 - loss: 0.0190 - val_accuracy: 0.9926 - val_loss: 0.0193
Epoch 17/30
407/407 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9935 - loss: 0.0202 - val_accuracy: 0.9929 - val_loss: 0.0199
Epoch 18/30
407/407 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9933 - loss: 0.0225 - val_accuracy: 0.9926 - val_loss: 0.0195
Epoch 19/30
407/407 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9924 - loss: 0.0207 - val_accuracy: 0.9923 - val_loss: 0.0191
Epoch 20/30
407/407 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9943 - loss: 0.0161 - val_accuracy: 0.9926 - val_loss: 0.0194
Epoch 21/30
407/407 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9931 - loss: 0.0203 - val_accuracy: 0.9926 - val_loss: 0.0193
Epoch 22/30
407/407 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9937 - loss: 0.0191 - val_accuracy: 0.9932 - val_loss: 0.0195
Epoch 23/30
407/407 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9931 - loss: 0.0187 - val_accuracy: 0.9932 - val_loss: 0.0197
Epoch 24/30
407/407 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.9936 - loss: 0.0170 - val_accuracy: 0.9929 - val_loss: 0.0192
Epoch 25/30
407/407 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.9933 - loss: 0.0192 - val_accuracy: 0.9926 - val_loss: 0.0187
Epoch 26/30
407/407 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9936 - loss: 0.0179 - val_accuracy: 0.9929 - val_loss: 0.0193
Epoch 27/30
407/407 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.9940 - loss: 0.0190 - val_accuracy: 0.9926 - val_loss: 0.0193
Epoch 28/30
407/407 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9944 - loss: 0.0167 - val_accuracy: 0.9929 - val_loss: 0.0194
Epoch 29/30
407/407 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9950 - loss: 0.0172 - val_accuracy: 0.9929 - val_loss: 0.0191
Epoch 30/30
407/407 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.9950 - loss: 0.0178 - val_accuracy: 0.9932 - val_loss: 0.0197

In [ ]:
loss, accuracy = model.evaluate(X_test, y_test)
print("Accuracy:", accuracy)

128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9963 - loss: 0.0127
Accuracy: 0.9943433403968811

In [ ]:
converter = tf.lite.TFLiteConverter.from_keras_model(model)

tflite_model = converter.convert()

with open("rain_model.tflite", "wb") as f:
    f.write(tflite_model)

Saved artifact at '/tmp/tmp2_4o6_9r'. The following endpoints are available:

* Endpoint 'serve'
  args_0 (POSITIONAL_ONLY): TensorSpec(shape=(None, 7), dtype=tf.float32, name='keras_tensor_3')
Output Type:
  TensorSpec(shape=(None, 3), dtype=tf.float32, name=None)
Captures:
  135368947264080: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135368947264848: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135368947264272: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135368947265040: TensorSpec(shape=(), dtype=tf.resource, name=None)

In [ ]:
converter.optimizations = [tf.lite.Optimize.DEFAULT]

tflite_quant_model = converter.convert()

with open("rain_model_quant.tflite", "wb") as f:
    f.write(tflite_quant_model)

Saved artifact at '/tmp/tmp1nirril9'. The following endpoints are available:

* Endpoint 'serve'
  args_0 (POSITIONAL_ONLY): TensorSpec(shape=(None, 7), dtype=tf.float32, name='keras_tensor_3')
Output Type:
  TensorSpec(shape=(None, 3), dtype=tf.float32, name=None)
Captures:
  135368947264080: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135368947264848: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135368947264272: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135368947265040: TensorSpec(shape=(), dtype=tf.resource, name=None)